### ISSUE TITLE
Not Sending Pushover message

### ISSUE THREAD

**Issue by Rizbe** [sensu-plugins/sensu-plugins-pushover#2]
```
{
  "handlers": {
    "pushover": {
      "type": "pipe",
      "command": "/opt/sensu/embedded/bin/handler-pushover.rb",
      "filter": "production"
    }
  },
  "pushover": {

    "_comment": "Single userkey / token pair",
    "userkey": "",
    "token": ""
  }
}
```

This is how I have my handler setup, I verified the key and token by writing a quick script to send me a message using my creds. Running Ubuntu 14.04 with latest sensu server and client.

`{"timestamp":"2016-06-16T19:01:09.790441+0000","level":"info","message":"processing event","event":{"client":{"name":"blue-app","address":"blue-something.com","environment":"production","subscriptions":["default","platform"],"version":"0.25.2","timestamp":1466103658},"check":{"command":"check-ports.rb -p 9410","interval":60,"subscribers":["platform"],"handlers":["pushover"],"name":"contact_service","issued":1466103669,"executed":1466103670,"duration":0.117,"output":"CheckPort CRITICAL: Connection refused by 0.0.0.0:9410\n","status":2,"type":"standard","history":["2","2","2","2","2","0","2","2","2","2","2","2","2","2","2"],"total_state_change":0},"occurrences":9,"action":"create","timestamp":1466103669,"id":"8b26dc25-e89a-4aa2-b461-42de74415f4d","last_state_change":1466103189,"last_ok":null}}
`

This plugin has never really worked for me, not sure if I am missing something.

**Comment by cwjohnston** [comment]
Hi @Rizbe, thanks for raising this issue. I am using this handler in my own environment successfully, but I have also explicitly defined `apiurl` property under the `pushover` configuration scope with the value "https://api.pushover.net/1/messages". I suspect the default isn't getting set for some reason. 

Will you please try explicitly setting this in your configuration, and let me know if it helps?

``` json
{ 
  "pushover": {
    "userkey": "",
    "token": "",
    "apiurl": "https://api.pushover.net/1/messages"
  }
}
```

**Comment by timm088** [comment]
@Rizbe you ever get this plugin to work?
